kind: pipeline
name: docker-compose

steps:
  - name: test
    image: docker:dind
    failure: ignore
    environment:
      MYSQL_ROOT_PASSWORD: asfsjdflksjdfh
      MYSQL_DATABASE: db_test
      MYSQL_USER: uniesi
      MYSQL_PASSWORD: $MYSQL_ROOT_PASSWORD
      DB_DIALECT: mariadb
      DB_NAME: $MYSQL_DATABASE
      DB_HOST: dblb
      DB_PORT: 3306
      DB_USER: $MYSQL_USER
      DB_PASS: $MYSQL_PASSWORD
      DB_TIMEZONE: America/Sao_Paulo
      APP_PORT: 8000
      APP_SECURE_PORT: 8443
      APP_SECRET: TESTE1cvcvcsdf545423
      STORAGE_TYPE: local
      BUCKET_NAME: ""
      REACT_APP_API_HOST: "http://127.0.0.1"
      REACT_APP_API_PORT: ${APP_PORT}
      REACT_PORT: 3000
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - docker stack rm teste
      - sleep 15 && docker stack deploy -c docker-compose.yml teste
      - sleep 240 && docker run -t --network=host curlimages/curl curl -f http://127.0.0.1:3000 || exit 1

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
