version: "3.7"
services:
  web:
    build: ./reactjs
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./web:/app/web
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  api:
    build: ./expressjs
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./api:/app/api
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
  db:
    build: ./database-service
    command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
