name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Pull in production server
        if: success()
        run: |
          mkdir ~/.ssh
          echo "Host githost" >> ~/.ssh/config
          echo "HostName campus1-iesi.ddns.net" >> ~/.ssh/config
          echo "Port 722 >> ~/.ssh/config
          echo "User mckatoo" >> ~/.ssh/config
          git remote add prod githost:/containers/uniesi/uniesiDocker.git
